name: Run Hello world
on: push

jobs:
  Hello:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repo
    uses: actions/checkout@v6

    -name: Setup python
    uses: actions/setup-python@v6
    with:
       python-version: '3.13'
    
    -run: python hello.py


